### PR TITLE
Fix parsing of access control headers (fixes #31)

### LINKED ISSUE #31: Access-Control-Request-Headers in firefox
I noticed angular running in firefox sends Access-Control-Request-Headers as comma separated string without spaces. This cause this to fail:

            $headers = $request->headers->get('Access-Control-Request-Headers');

            if (is_string($headers)) {
                foreach (explode(', ', $headers) as $header) {

I added a simple middleware to deal with it, but it would be great to have it in package. Eg. support both explode(', '.. and explode(','..

### PR DESCRIPTION
**Pull request by cniska**

### CODE REVIEW

File: tests/unit/CorsServiceTest.php [hunk 1]
```diff
@@ -164,12 +177,36 @@ public function testHandlePreflightRequest()
...
+            'allow_methods' => ['post'],
+            'allow_headers' => ['accept', 'authorization', 'content-type'],
+        ]);
+
+        $this->request = new Request;
+
+        $this->specify('regression test for issue #31', function () {
+            $this->request->headers->set('Origin', 'http://foo.com');
+            $this->request->headers->set('Access-Control-Request-Method', 'POST');
+            $this->request->headers->set('Access-Control-Request-Headers', 'accept,authorization,content-type');
```
Comment (Jalle19) [inline tests/unit/CorsServiceTest.php]: You are not testing with spaces here, can you add a space after at least one of the commas?

**Review by Jalle19 — CHANGES_REQUESTED** [review]

**Comment by cniska** [comment]
@Jalle19 I changed the test case as requested.

**Review by Jalle19 — APPROVED** [review]
